name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.GPUL_DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.GPUL_DOCKER_HUB_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gpul/hack-udc-landing
        
      - name: Docker Push
        run: docker push gpul/hack-udc-landing